export const State = [
    { code: "1010", label: "Phra Nakhon" },
    { code: "1011", label: "Dusit" },
    { code: "1012", label: "Nong Chok" },
    { code: "1013", label: "Bang Rak" },
    { code: "1014", label: "Bang Khen" },
    { code: "1015", label: "Bang Kapi" },
    { code: "1016", label: "Pathum Wan" },
    { code: "1017", label: "Pom Prap Sattru Phai" },
    { code: "1018", label: "Phra Khanong" },
    { code: "1019", label: "Min Buri" },
    { code: "1020", label: "Lat Krabang" },
    { code: "1021", label: "Yan Nawa" },
    { code: "1022", label: "Samphanthawong" },
    { code: "1023", label: "Phaya Thai" },
    { code: "1024", label: "Thon Buri" },
    { code: "1025", label: "Bangkok Yai" },
    { code: "1026", label: "Huai Khwang" },
    { code: "1027", label: "Khlong San" },
    { code: "1028", label: "Taling Chan" },
    { code: "1029", label: "Bangkok Noi" },
    { code: "1030", label: "Bang Khun Thian" },
    { code: "1031", label: "Phasi Charoen" },
    { code: "1032", label: "Nong Khaem" },
    { code: "1033", label: "Rat Burana" },
    { code: "1034", label: "Bang Phlat" },
    { code: "1035", label: "Din Daeng" },
    { code: "1036", label: "Bueng Kum" },
    { code: "1037", label: "Sathon" },
    { code: "1038", label: "Bang Sue" },
    { code: "1039", label: "Chatuchak" },
    { code: "1040", label: "Bang Kho Laem" },
    { code: "1041", label: "Prawet" },
    { code: "1042", label: "Khlong Toei" },
    { code: "1043", label: "Suan Luang" },
    { code: "1044", label: "Chom Thong" },
    { code: "1045", label: "Don Mueang" },
    { code: "1046", label: "Ratchathewi" },
    { code: "1047", label: "Lat Phrao" },
    { code: "1048", label: "Watthana" },
    { code: "1049", label: "Bang Khae" },
    { code: "1050", label: "Lak Si" },
    { code: "1051", label: "Sai Mai" },
    { code: "1052", label: "Khan Na Yao" },
    { code: "1053", label: "Saphan Sung" },
    { code: "1054", label: "Wang Thonglang" },
    { code: "1055", label: "Khlong Sam Wa" },
    { code: "1056", label: "Bang Na" },
    { code: "1057", label: "Thawi Watthana" },
    { code: "1058", label: "Tha Kham" },
    { code: "1059", label: "Thung Khru" },
    { code: "1060", label: "Bang Bon" }
  ]