export const province = [
    { code: "10", label: "Bangkok" },
    { code: "11", label: "Samut Prakan" },
    { code: "12", label: "Nonthaburi" },
    { code: "13", label: "Pathum Thani" },
    { code: "14", label: "Phra Nakhon Si Ayutthaya" },
    { code: "15", label: "Ang Thong" },
    { code: "16", label: "Lopburi" },
    { code: "17", label: "Sing Buri" },
    { code: "18", label: "Chai Nat" },
    { code: "19", label: "Saraburi" },
    { code: "20", label: "Chonburi" },
    { code: "21", label: "Rayong" },
    { code: "22", label: "Chanthaburi" },
    { code: "23", label: "Trat" },
    { code: "24", label: "Chachoengsao" },
    { code: "25", label: "Prachinburi" },
    { code: "26", label: "Nakhon Nayok" },
    { code: "27", label: "Sa Kaeo" },
    { code: "30", label: "Nakhon Ratchasima" },
    { code: "31", label: "Buri Ram" },
    { code: "32", label: "Surin" },
    { code: "33", label: "Si Sa Ket" },
    { code: "34", label: "Ubon Ratchathani" },
    { code: "35", label: "Yasothon" },
    { code: "36", label: "Chaiyaphum" },
    { code: "37", label: "Amnat Charoen" },
    { code: "38", label: "Nong Bua Lam Phu" },
    { code: "39", label: "Khon Kaen" },
    { code: "40", label: "Udon Thani" },
    { code: "41", label: "Loei" },
    { code: "42", label: "Nong Khai" },
    { code: "43", label: "Maha Sarakham" },
    { code: "44", label: "Roi Et" },
    { code: "45", label: "Kalasin" },
    { code: "46", label: "Sakon Nakhon" },
    { code: "47", label: "Nakhon Phanom" },
    { code: "48", label: "Mukdahan" },
    { code: "49", label: "Chiang Mai" },
    { code: "50", label: "Lamphun" },
    { code: "51", label: "Lampang" },
    { code: "52", label: "Uttaradit" },
    { code: "53", label: "Phrae" },
    { code: "54", label: "Nan" },
    { code: "55", label: "Phayao" },
    { code: "56", label: "Chiang Rai" },
    { code: "57", label: "Mae Hong Son" },
    { code: "60", label: "Nakhon Sawan" },
    { code: "61", label: "Uthai Thani" },
    { code: "62", label: "Kamphaeng Phet" },
    { code: "63", label: "Tak" },
    { code: "64", label: "Sukhothai" },
    { code: "65", label: "Phitsanulok" },
    { code: "66", label: "Phichit" },
    { code: "67", label: "Phetchabun" },
    { code: "70", label: "Ratchaburi" },
    { code: "71", label: "Kanchanaburi" },
    { code: "72", label: "Suphan Buri" },
    { code: "73", label: "Nakhon Pathom" },
    { code: "74", label: "Samut Sakhon" },
    { code: "75", label: "Samut Songkhram" },
    { code: "76", label: "Phetchaburi" },
    { code: "77", label: "Prachuap Khiri Khan" },
    { code: "80", label: "Nakhon Si Thammarat" },
    { code: "81", label: "Krabi" },
    { code: "82", label: "Phang Nga" },
    { code: "83", label: "Phuket" },
    { code: "84", label: "Surat Thani" },
    { code: "85", label: "Ranong" },
    { code: "86", label: "Chumphon" },
    { code: "90", label: "Songkhla" },
    { code: "91", label: "Satun" },
    { code: "92", label: "Trang" },
    { code: "93", label: "Phatthalung" },
    { code: "94", label: "Pattani" },
    { code: "95", label: "Yala" },
    { code: "96", label: "Narathiwat" }
  ]