export const initialState = {
  openModalPO: false,
  openModalMemo: false,
  selectedItems: [],
  useDiscountPercent: false,
  useDiscountAmount: false,
  discount_percent: 0,
  discount_amount: 0,
  useVAT: false,
  vatAmount: 0,
  otherCharge: 0,
};

export const initialData = [
  {
    doc_date: "29/01/2024",
    no: "PO2024010002",
    account: "Mutto",
    stone: "Diamond",
    shape: "Round",
    size: "4.1 MM",
    color: "Pink Diamond",
    cutting: "Normal Cut",
    quality: "AAA",
    clarity: "VS1",
    cer_type: "GIA",
    cer_no: "1418593884469 ",
    pcs: 2,
    weight: 1.25,
    price: 18900,
    unit_price: "pcs",
    amount: 0,
    discount_percent: 0,
    discount_amount: 0,
    labour_type: "Recutting",
    labour_type: "Recutting",
    labour_price: 20,
    labour_unit: "pcs",
    labour_unit: "pcs",
    total_amount: 0,
    disabled: true,
    backgroundColor: "#F0F0F0",
    type: "text",
  },
  {
    doc_date: "29/01/2024",
    no: "PO2024010003",
    account: "Kutto",
    stone: "Diamond",
    shape: "Round",
    size: "4.1 MM",
    color: "Pink Diamond",
    cutting: "Normal Cut",
    quality: "AAA",
    clarity: "VS1",
    cer_type: "GIA",
    cer_no: "1418593884469 ",
    pcs: 2,
    weight: 2.25,
    price: 24900,
    unit_price: "pcs",
    amount: 0,
    discount_percent: 0,
    discount_amount: 0,
    labour_type: "Recutting",
    labour_price: 20,
    labour_unit: "pcs",
    total_amount: 0,
    disabled: true,
    backgroundColor: "#F0F0F0",
    type: "text",
  },
  {
    doc_date: "29/01/2024",
    no: "PO2024010004",
    account: "Rindo",
    stone: "Diamond",
    shape: "Round",
    size: "4.1 MM",
    color: "Pink Diamond",
    cutting: "Normal Cut",
    quality: "AAA",
    clarity: "VS1",
    cer_type: "GIA",
    cer_no: "1418593884469 ",
    pcs: 2,
    weight: 0.125,
    price: 4900,
    unit_price: "pcs",
    amount: 0,
    discount_percent: 0,
    discount_amount: 0,
    labour_type: "Recutting",
    labour_price: 20,
    labour_unit: "pcs",
    total_amount: 0,
    disabled: true,
    backgroundColor: "#F0F0F0",
    type: "text",
  },
];

export const initialData2 = [
  {
    doc_date: "29/01/2024",
    no: "MO2024010002",
    account: "Moshi",
    stone: "Diamond",
    shape: "Round",
    size: "4.1 MM",
    color: "Pink Diamond",
    cutting: "Normal Cut",
    quality: "AAA",
    clarity: "VS1",
    cer_type: "GIA",
    cer_no: "1418593884469 ",
    pcs: 2,
    weight: 1.25,
    price: 14900,
    unit_price: "pcs",
    amount: 0,
    discount_percent: 0,
    discount_amount: 0,
    labour_type: "Recutting",
    labour_price: 20,
    labour_unit: "pcs",
    total_amount: 0,
    disabled: true,
    backgroundColor: "#F0F0F0",
    type: "text",
  },
  {
    doc_date: "29/01/2024",
    no: "MO2024010003",
    account: "Kaito",
    stone: "Diamond",
    shape: "Round",
    size: "4.1 MM",
    color: "Pink Diamond",
    cutting: "Normal Cut",
    quality: "AAA",
    clarity: "VS1",
    cer_type: "GIA",
    cer_no: "1418593884469 ",
    pcs: 2,
    weight: 2.25,
    price: 28900,
    unit_price: "pcs",
    amount: 0,
    discount_percent: 0,
    discount_amount: 0,
    labour_type: "Recutting",
    labour_price: 20,
    labour_unit: "pcs",
    total_amount: 0,
    disabled: true,
    backgroundColor: "#F0F0F0",
    type: "text",
  },
  {
    doc_date: "29/01/2024",
    no: "MO2024010004",
    account: "Jakarot",
    stone: "Diamond",
    shape: "Round",
    size: "4.1 MM",
    color: "Pink Diamond",
    cutting: "Normal Cut",
    quality: "AAA",
    clarity: "VS1",
    cer_type: "GIA",
    cer_no: "1418593884469 ",
    pcs: 2,
    weight: 0.125,
    price: 8900,
    unit_price: "pcs",
    amount: 0,
    discount_percent: 0,
    discount_amount: 0,
    labour_type: "Recutting",
    labour_price: 20,
    labour_unit: "pcs",
    total_amount: 0,
    disabled: true,
    backgroundColor: "#F0F0F0",
    type: "text",
  },
];

export const newAddTemplate = {
  doc_date: "",
  no: "",
  account: "",
  stone: "",
  shape: "",
  size: "",
  color: "",
  cutting: "",
  quality: "",
  clarity: "",
  pcs: 0,
  weight: 0,
  price: 0,
  unit_price: "",
  amount: 0,
  discount_percent: 0,
  discount_amount: 0,
  labour_type: "",
  labour_price: 0,
  labour_unit: "",
  total_amount: 0,
  cer_type: "",
  cer_no: "",
  cer_type: "",
  ref_no: "",
  remark: "",
  lot_no: ""
};
